# Generated by Django 4.2.1 on 2023-10-05 17:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('dailyrecord_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('measuredFood', models.CharField(max_length=100, null=True)),
                ('expectedQuantity', models.CharField(max_length=100, null=True)),
                ('food', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=50)),
                ('tquantity', models.IntegerField(default=0)),
                ('tamount', models.IntegerField(default=0)),
            ],
        ),
    ]
