# Generated by Django 4.2.1 on 2023-10-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Records',
        ),
    ]
